spring.application.name=OnDemandServiceBookingPlatform

server.port=1086

spring.datasource.url=jdbc:postgresql://localhost:5432/OnDemandServiceBookingPlatform
spring.datasource.username=${postgres_username}
spring.datasource.password=${postgres_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.security.user.name=venkat
#spring.security.user.password=venkat
